#!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

echo '🔨👷 Checking code style before committing...'

# Check Prettier standards
npm run check-format ||
(
    echo '❌🎨 Code formatting check failed! 🎨❌
            Please run "npm run format" to fix styling issues, then try committing again.';
    false;
)

# If everything passes... Now we can commit
echo '✅🎉 All checks passed! Committing your beautiful code... ✅🎉'

